= ANTLR 4: generator

:source-highlighter: highlightjs
:revealjs_hash: true
:icons: font
:customcss: https://codepen.io/anstreth/pen/WNvVedL.css
:revealjs_theme: white
:stem: latexmath


https://wuciawe.github.io/java/2017/04/12/notes-on-antlr4.html[Good ANTLR book notes]

https://dl.icdst.org/pdfs/files3/a91ace57a8c4c8cdd9f1663e1051bf93.pdf[The Definitive ANTLR 4 Reference (Book)]

https://www.researchgate.net/publication/273188534_Adaptive_LL_Parsing_The_Power_of_Dynamic_Analysis?enrichId=rgreq-4c62e82b87aa8e4f9457ae5950369e20-XXX&enrichSource=Y292ZXJQYWdlOzI3MzE4ODUzNDtBUzo0Njc1MjUyMDYwNTY5NjBAMTQ4ODQ3ODEwMzQ1Mg==&el=1_x_3&_esc=publicationCoverPdf[Adaptive LL(*) Parsing: The Power of Dynamic Analysis]

https://www.antlr.org/papers/LL-star-PLDI11.pdf[LL(*): The Foundation of the ANTLR Parser Generator]

== Parsing algorithm

ANTLR use ALL(*) parsing algorithm (Adaptive LL)

incrementally builds DFA considering just the lookahead sequences it has been instead of all *possible* sequences.

=== Lexer
Generated automatically from grammar. Use variation of ALL(\*) that fully
matches tokens instead of just predicting productions like ALL(\*) parsers do. After *warm-up(???)* the lexer will have built a DFA.

==== Two-stage parsing
*Stage one*: try handle parsing with `SLL` (Strong LL) -- predication algorithm that don't use a stack state. `SLL` is weaker but faster than `LL`.

Grammar that exhibits a stack-sensitive decision in nonterminal A:

```
S → xB | yC 
B → Aa 
C → Aba 
A → b | eps
```
For string lookahead `ba` predicts `A → b` when `B` invokes `A` but predicts `A → eps` when `C` invokes `A`. `SLL` can't parse this case.

*Stage two*:  If `SLL` finds a syntax error, it might have found an `SLL` weakness or a real syntax error, so we have to retry the entire input using optimized `LL`. 
 
 "Nonetheless, the second (LL) stage must remain to ensure correctness."

=== Resolving ambiguity
Use semantic predicates and production order (choose first alternative).


=== ATN vs RSM
 
 #todo -- they look like one thing

== Grammar
Аny context-free grammar that does not contain indirect or hidden left-recursion:

```g4
expr : expo // indirectly invokes expr left recursively via expo
    | ...
    ;
expo : expr '^'<assoc=right> expr ;
```
Direct recursion supported through grammar rewriting prior to parser generation.

 Indirect or hidden recursion not supported "because these forms are much less common and removing all left recursion can lead to exponentially-big transformed grammars".
