name: GitHub Pages Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
    upload:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - run: "sudo apt-get install asciidoctor"
            
            - run: "asciidoctor 'Parsers/CNP/index.adoc' -D _site/fl"
            - run: "cp -r 'Parsers/CNP/media' _site/fl"

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v1.0.8

    deploy:
        needs: upload
        runs-on: ubuntu-22.04

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
